#!/bin/sh


set -e


# do we have the commands we need
for i in wget grep chmod rm mktemp; do
	if [ -z "$(command -v $i)" ]; then
		echo "Command ${i} not availabled, exiting with status 1"
		exit 1
	fi
done


# we need a directory in tmp to work with
tmp_dir="$(mktemp -d)/"
if [ ! -d "$tmp_dir" ]; then
	echo "Failed to create ${tmp_dir}, exiting with status 1"
	exit 1
fi


clean_up() {
	# Remove temporary directory
	if [ -d "$tmp_dir" ]; then
		rm -r "$tmp_dir"
	fi

	# Ignore the EXIT signal for trap
	trap '' EXIT

	# if we have exit code exit with it if we don't use 255
	if [ -n "$?" ]; then
		exit "$?"
	else
		exit "255"
	fi
}



# trap unexpected terminations of the script and clean up
trap 'exit 1' HUP INT QUIT TERM
trap 'clean_up' EXIT


# we need a local bin to move to
if [ ! -d "/usr/local/bin/" ]; then
	echo "Why don't you have a /usr/local/bin/?, exiting with status 1"
	exit "1"
fi


# get the current version and store it
if [ -n "$(command -v youtube-dl)" ]; then
	current_version="$(youtube-dl --version \
	                | grep -o -E '[0-9]{4}\.[0-9]{2}\.[0-9]{2}')"
	if [ -z "$current_version" ]; then
		current_version="NULL"
	fi
else
	current_version="NULL"
fi



# fetch the sha so we can check the the version
wget -q -4 -T 180 "https://yt-dl.org/downloads/latest/SHA2-512SUMS" \
-O "${tmp_dir}sha2-512sums"
if [ "$?" != "0" ]; then
	echo "Couldn't fetch sha2-512sums, exiting with status 1"
	exit "1"
fi


# compare the current version with the next
if [ "$current_version" != "NULL" ]; then
	remote_version="$(grep -o -E '[0-9]{4}\.[0-9]{2}\.[0-9]{2}' \
		       "${tmp_dir}sha2-512sums")"
	if [ -z "$remote_version" ]; then
		echo "Couldn't get remote version, exiting with status 1"
		exit "1"
	fi
	if [ "$current_version" = "$remote_version" ]; then
		# we're up to date exit cleanly
		exit "0"
	fi
fi


# fetch the files we need
wget -q -4 -T 180 "https://yt-dl.org/downloads/latest/youtube-dl" \
-O "${tmp_dir}youtube-dl"
if [ "$?" != "0" ]; then
	echo "Couldn't fetch youtube-dl, exiting with status 1"
	exit "1"
fi


# sha has to match
if [ "$(grep -q -i sha512sum "${tmp_dir}youtube-dl" \
   | awk '{print $1}' "${tmp_dir}sha2-512sums")" ]; then
	# move our file and chmod it
	mv "${tmp_dir}youtube-dl" "/usr/local/bin/youtube-dl"
	chmod +x "/usr/local/bin/youtube-dl"
	if [ "$current_version" = "NULL" ]; then
		echo "youtube-dl version ${remote_version} installed"
		exit "0"
	else
		echo "youtube-dl updated from version ${current_version} to ${remote_version}"
		exit "0"
	fi
else
	echo "Checksum did not match! Exiting with status 1"
	exit "1"
fi

